# Generated by Django 4.0.4 on 2022-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=250)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')])),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
