# Generated by Django 4.0.4 on 2022-05-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
